
name: Scheduler task 秋田のみち情報

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  scheduledTask:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      LIVECAMERA_GOOGLE_API_TOKEN: ${{ secrets.GOOGLE_API_TOKEN }}
      PUBLISH_SERVER_HOST: ${{ secrets.PUBLISH_SERVER_HOST }}
      PUBLISH_SERVER_PORT: ${{ secrets.PUBLISH_SERVER_PORT }}
      PUBLISH_SERVER_USER: ${{ secrets.PUBLISH_SERVER_USER }}
      SSH_KEY_FILE: ${{ github.workspace }}/.ssh/id_ecdsa
      SSH_CONFIG_FILE: ${{ github.workspace }}/.ssh/config
      SSH_KNOWN_HOSTS_FILE: ${{ github.workspace }}/.ssh/known_hosts
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Check OS environment
        run: |
          which ip && ip address
          which ip && ip route
      - name: Setup global environment
        run: |
          echo ${GITHUB_WORKSPACE}/node_modules/.bin >> ${GITHUB_PATH}
      - name: Setup sync environment
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/.ssh/
          echo "${{ secrets.PUBLISH_SERVER_SSH_KEY }}" > ${SSH_KEY_FILE}
          chmod 600 ${SSH_KEY_FILE}
          echo "" > ${SSH_KNOWN_HOSTS_FILE}
          echo "${{ secrets.PUBLISH_SERVER_HOST_KEY }}" >> ${SSH_KNOWN_HOSTS_FILE}
          echo "" > ${SSH_CONFIG_FILE}
          echo "IdentitiesOnly=true" >> ${SSH_CONFIG_FILE}
          echo "UserKnownHostsFile=${SSH_KNOWN_HOSTS_FILE}" >> ${SSH_CONFIG_FILE}
      - name: Prepare packages
        run: |
          npm install
      - name: Run Task Scheduler
        run: |
         npm run schedule -- 7439edcfad2c9eaaaf65
